services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app_prod
    restart: unless-stopped
    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage

    command: php artisan serve --host=0.0.0.0 --port=8000

    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}

    networks:
      - web
      - internal

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.todo-api.rule=Host(`todo.e-api.ru`)"
      - "traefik.http.routers.todo-api.entrypoints=websecure"
      - "traefik.http.routers.todo-api.tls.certresolver=myresolver"
      - "traefik.http.services.todo-api.loadbalancer.server.port=8000"

  nginx:
    image: nginx:alpine
    container_name: api_nginx_prod
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.todo-nginx.rule=Host(`todo.e-api.ru`)"
      - "traefik.http.routers.todo-nginx.entrypoints=websecure"
      - "traefik.http.routers.todo-nginx.tls.certresolver=myresolver"
      - "traefik.http.services.todo-nginx.loadbalancer.server.port=80"

networks:
  web:
    external: true
    name: web
    attachable: true
  internal:
    driver: bridge
