version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app_prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
    networks:
      - traefik
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      
      # HTTP роутер
      - "traefik.http.routers.todo-api.rule=Host(`todo.e-api.ru`)"
      - "traefik.http.routers.todo-api.entrypoints=web"
      - "traefik.http.routers.todo-api.middlewares=redirect-to-https"
      
      # HTTPS роутер
      - "traefik.http.routers.todo-api-secure.rule=Host(`todo.e-api.ru`)"
      - "traefik.http.routers.todo-api-secure.entrypoints=websecure"
      - "traefik.http.routers.todo-api-secure.tls=true"
      - "traefik.http.routers.todo-api-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.todo-api-secure.service=todo-api"
      
      # Сервис
      - "traefik.http.services.todo-api.loadbalancer.server.port=9000"
      
      # Middleware для редиректа HTTP -> HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  traefik:
    external: true
  internal:
    driver: bridge

